version: '3'

services:
  web:
    build: ./apache
    ports:
    - "8080:80"
    working_dir: /var/www/html
    volumes:
      - ./public:/var/www/html

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
